[SwitchyOmega Conditions]
@with result

*google* +proxy
*facebook* +proxy
*youtube* +proxy
*twitter* +proxy
*instagram* +proxy
*gmail* +proxy
*twimg* +proxy
*medium* +proxy
*github* +proxy
*appspot* +proxy
*stackoverflow* +proxy
*gstatic* +proxy
*wikipedia* +proxy
*wikimedia* +proxy
*reddit* +proxy
*quora* +proxy
*ggpht* +proxy
*ytimg* +proxy
*nytimes* +proxy
*nytcn* +proxy
*cloudfront* +proxy
*slashdot* +proxy
*phncdn* +proxy
*v2ray* +proxy
*tensorflow* +proxy
*imgur* +proxy
*sstatic* +proxy
*telegram* +proxy
*telesco* +proxy
*telegra* +proxy
*coursera* +proxy
*feedly* +proxy
*apache* +proxy
*ycombinator* +proxy
*producthunt* +proxy
*9to5mac* +proxy
*bloomberg* +proxy
*devpost* +proxy
*mitre* +proxy
*vimeo* +proxy
*pinterest* +proxy
*pinimg* +proxy
*towardsdatascience* +proxy
*slideshare* +proxy
*keras* +proxy
*elastic* +proxy
*chromeunboxed* +proxy
*theguardian* +proxy
*v2ex* +proxy
*deepmind* +proxy
*gettyimages* +proxy
*notion* +proxy
*manjaro* +proxy
*economist* +proxy
*vmware* +proxy
*heroku* +proxy
*openai* +proxy
*discord* +proxy
*civitai* +proxy
*reuters* +proxy
*luckydesigner* +proxy
*gravatar* +proxy
*.youtu.be* +proxy
*.t.co* +proxy
*.fb.com* +proxy
*.fc2.com* +proxy
*.nyt.com* +proxy
*.redd.it* +proxy
*.bit.ly* +proxy
*.t.me* +proxy
*.live.com* +proxy
*.gitlab.io* +proxy
*.bbc.com* +proxy
*.bbc.co.uk* +proxy
*.vercel.app* +proxy
*.x.com* +proxy


* +direct
