name: CI

on:
  push:
    paths: d.conf

jobs:
  build:
    name: defalut
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
      - name: c
        run: |
          python c.py
      - name: commit
        run: |
          git config --global user.email dingody@qq.com
          git config --global user.name dingody
          git add .
          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
