name: CI

on:
  push:
    paths: d.conf

jobs:
  build:
    name: defalut
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
      - name: test
        run: |
          cd py
          python test.py
